 services:
  db:
    image: jumice93/personasbbdd
    container_name: contenedorpersonasbbdd
    ports:
      - "3306:3306"
  php:
    image: jumice93/personasbbdd
    container_name: contenedorpersonasapp
    ports:
      - "8080:80"
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: contenedorPhpMyAdmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: contrasenyaRoot
    ports:
      - "8081:80"
    depends_on:
      - db
